import { diceChance,diceMultiplier } from "../casino-core.js";
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
export function mount(container,ctx){let bet=100,target=50,direction="under",busy=false,visible=false,auto=false,history=[];
 container.innerHTML=`<section class="dc"><main class="dc-play"><header>DICE <small>99% RTP · PROVABLY FAIR</small></header><div class="dc-result">--<small>SET YOUR TARGET</small></div><div class="dc-track"><div class="dc-zone"></div><i></i><input type="range" min="1" max="99" step=".01" value="50"><div><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div></div><div class="dc-history"></div></main><aside class="dc-panel"><div class="dc-toggle"><button data-dir="under">ROLL UNDER</button><button data-dir="over">ROLL OVER</button></div><label>TARGET<input class="dc-target" type="number" min="1" max="99" step=".01" value="50"></label><div class="dc-stats"><span>WIN CHANCE<b class="dc-chance"></b></span><span>MULTIPLIER<b class="dc-multi"></b></span><span>PAYOUT<b class="dc-payout"></b></span></div><label>BET AMOUNT<div class="dc-bet"><input type="number" min="1" step=".01" value="100"><button data-scale=".5">½</button><button data-scale="2">2×</button><button data-scale="max">MAX</button></div></label><button class="dc-roll">ROLL <span>SPACE</span></button><label class="dc-auto"><input type="checkbox"> QUICK AUTO-ROLL <input class="dc-count" type="number" min="1" max="100" value="10"> ROLLS</label></aside></section>`;const $=s=>container.querySelector(s);
 function validTarget(n,dir){return dir==="under"?clamp(n,1,98):clamp(n,2,99)}
 function render(){target=Math.round(validTarget(target,direction)*100)/100;const chance=diceChance(target,direction),multi=diceMultiplier(chance);$(".dc-target").value=target.toFixed(2);$(".dc-track input").value=target;$(".dc-zone").style.cssText=direction==="under"?`left:0;width:${target}%`:`left:${target}%;width:${100-target}%`;container.querySelectorAll("[data-dir]").forEach(x=>x.classList.toggle("active",x.dataset.dir===direction));$(".dc-chance").textContent=`${chance.toFixed(2)}%`;$(".dc-multi").textContent=`${multi.toFixed(4)}×`;$(".dc-payout").textContent=`${ctx.money(bet*multi)} CR`;$(".dc-bet input").value=bet;$(".dc-roll").disabled=busy||bet<1||bet>ctx.balance();$(".dc-history").innerHTML=history.slice(-14).reverse().map(x=>`<b class="${x.won?"won":"lost"}">${x.roll.toFixed(2)}</b>`).join("")}
 async function roll(fromAuto=false){if(busy||bet>ctx.balance())return false;busy=true;render();let res;try{res=await ctx.request("/casino/dice",{bet,target,direction},{reveal:true})}catch(e){busy=false;auto=false;render();ctx.toast(e.message,"loss");return false}const r=res.round,display=$(".dc-result"),marker=$(".dc-track i");display.className="dc-result rolling";display.firstChild.textContent="··";marker.style.left=`${r.roll}%`;await new Promise(ok=>setTimeout(ok,ctx.reducedMotion()?80:650));res.reveal();display.className=`dc-result ${r.won?"won":"lost"}`;display.innerHTML=`${r.roll.toFixed(2)}<small>${r.won?`WIN · ${r.multiplier.toFixed(2)}×`:`MISSED ${r.direction.toUpperCase()} ${r.target.toFixed(2)}`}</small>`;history.push({roll:r.roll,won:r.won});if(r.won)ctx.sound(800,.12,"triangle",.05);else ctx.sound(160,.2,"sawtooth",.03);busy=false;render();return true}
 async function runAuto(){if(auto)return;auto=true;let n=clamp(+$(`.dc-count`).value||1,1,100);while(auto&&n--&&visible&&bet<=ctx.balance()){if(!await roll(true))break;await new Promise(ok=>setTimeout(ok,ctx.reducedMotion()?30:180))}auto=false}
 container.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.dir){direction=b.dataset.dir;target=validTarget(target,direction);render()}else if(b.dataset.scale){bet=b.dataset.scale==="max"?Math.max(1,ctx.balance()):Math.max(1,Math.round(bet*+b.dataset.scale*100)/100);render()}else if(b.classList.contains("dc-roll"))$(".dc-auto input").checked?runAuto():roll()});container.addEventListener("input",e=>{if(e.target.matches(".dc-track input,.dc-target")){target=+e.target.value;render()}if(e.target.matches(".dc-bet input")){bet=Math.max(1,+e.target.value||1);render()}});document.addEventListener("keydown",e=>{if(visible&&e.code==="Space"&&!e.repeat&&!e.target.closest?.("input,select,textarea")){e.preventDefault();roll()}});ctx.onModeChange(()=>{auto=false;busy=false;history=[];render()});render();return{show(){visible=true;render()},hide(){visible=false;auto=false}}}
