import { ROULETTE_RED } from "../casino-core.js";

const ORDER=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const CHIPS=[1,5,25,100,500,2500];
const COLORS=["#9aa3b8","#53e7ff","#2ee59d","#c7ff36","#ae70ff","#ff4fd8"];
const key=(t,v)=>`${t}:${v??""}`;
const label=(t,v)=>t==="straight"?v:t==="dozen"?`${v}${["ST","ND","RD"][v-1]} 12`:t==="column"?`${v} · 2:1`:({low:"1–18",high:"19–36",odd:"ODD",even:"EVEN",red:"RED",black:"BLACK"}[t]);

export function mount(container,ctx){
 let bets=new Map(), last=null, undo=[], chip=5,busy=false,visible=false,history=load(),angle=0,ballAngle=0;
 function sk(){return `number-zero-roulette:${ctx.mode()}`}; function load(){try{return JSON.parse(localStorage.getItem(sk()))||[]}catch{return[]}}
 const cells=[]; for(let row=0;row<3;row++)for(let col=0;col<12;col++){const n=3*col+(3-row);cells.push(`<button class="rl-bet rl-num ${ROULETTE_RED.includes(n)?"red":"black"}" data-t="straight" data-v="${n}"><b>${n}</b><i></i></button>`)}
 const wheel=ORDER.map((n,i)=>`<g transform="rotate(${i*360/37} 100 100)"><path d="M100 8 A92 92 0 0 1 115.55 9.32 L108.45 50.72 A50 50 0 0 0 100 50Z" class="${n===0?"green":ROULETTE_RED.includes(n)?"red":"black"}"/><text x="100" y="22" transform="rotate(${-i*360/37} 100 22)">${n}</text></g>`).join("");
 container.innerHTML=`<section class="rl"><main class="rl-play"><div class="rl-wheel"><svg viewBox="0 0 200 200"><g class="rl-rotor">${wheel}<circle cx="100" cy="100" r="47"/><circle cx="100" cy="100" r="29" class="hub"/></g><circle class="rl-ball" cx="100" cy="18" r="4"/></svg><div class="rl-result">PLACE YOUR BETS</div></div><div class="rl-table"><button class="rl-bet rl-zero green" data-t="straight" data-v="0"><b>0</b><i></i></button><div class="rl-grid">${cells.join("")}</div><div class="rl-cols">${[1,2,3].map(v=>`<button class="rl-bet" data-t="column" data-v="${v}">2:1<i></i></button>`).join("")}</div><div class="rl-wide">${[1,2,3].map(v=>`<button class="rl-bet" data-t="dozen" data-v="${v}">${label("dozen",v)}<i></i></button>`).join("")}</div><div class="rl-wide six">${[["low"],["even"],["red"],["black"],["odd"],["high"]].map(([t])=>`<button class="rl-bet ${t}" data-t="${t}">${label(t)}<i></i></button>`).join("")}</div></div></main><aside class="rl-panel"><header><b>EUROPEAN ROULETTE</b><small>SINGLE ZERO · 35:1</small></header><div class="rl-chips">${CHIPS.map((v,i)=>`<button data-chip="${v}" style="--chip:${COLORS[i]}">${v>=1000?v/1000+"K":v}</button>`).join("")}</div><div class="rl-tools">${["undo","clear","rebet","double"].map(x=>`<button data-tool="${x}">${x==="double"?"2×":x.toUpperCase()}</button>`).join("")}</div><div class="rl-total"><span>TOTAL BET</span><b>0.00 CR</b></div><button class="rl-spin">SPIN <span>SPACE</span></button><div class="rl-summary"></div><div class="rl-history"></div></aside></section>`;
 const $=s=>container.querySelector(s);
 function render(){container.querySelectorAll(".rl-bet").forEach(el=>{const a=bets.get(key(el.dataset.t,el.dataset.v==null?null:+el.dataset.v))||0;el.querySelector("i").textContent=a?ctx.money(a):""});container.querySelectorAll("[data-chip]").forEach(x=>x.classList.toggle("active",+x.dataset.chip===chip));const total=[...bets.values()].reduce((a,b)=>a+b,0);$(".rl-total b").textContent=`${ctx.money(total)} CR`;$(".rl-spin").disabled=busy||!total||total>ctx.balance();$(".rl-history").innerHTML=`<small>RECENT</small>${history.slice(-12).reverse().map(n=>`<b class="${n===0?"green":ROULETTE_RED.includes(n)?"red":"black"}">${n}</b>`).join("")}`}
 function set(next){undo.push(new Map(bets));bets=next;render()}
 async function spin(){if(busy||!bets.size)return;busy=true;render();container.querySelectorAll(".win").forEach(x=>x.classList.remove("win"));const placed=[...bets].map(([k,amount])=>{const [type,v]=k.split(":");return {type,...(v!==""?{value:+v}:{}),amount}}),mode=ctx.mode();let res;try{res=await ctx.request("/casino/roulette",{bets:placed},{reveal:true})}catch(e){busy=false;render();ctx.toast(e.message,"loss");return}const r=res.round,idx=ORDER.indexOf(r.number),turns=ctx.reducedMotion()?1:5;angle+=turns*360+(360-idx*360/37)-(angle%360);$(".rl-rotor").style.transform=`rotate(${angle}deg)`;ballAngle-=(turns+2)*360;$(".rl-ball").style.transform=`rotate(${ballAngle}deg)`;await new Promise(ok=>setTimeout(ok,ctx.reducedMotion()?120:2300));res.reveal();if(ctx.mode()!==mode)return;last=new Map(bets);history.push(r.number);history=history.slice(-30);localStorage.setItem(sk(),JSON.stringify(history));container.querySelectorAll(".rl-bet").forEach(el=>{const b=r.bets.find(x=>x.type===el.dataset.t&&(x.value??null)===(el.dataset.v==null?null:+el.dataset.v));if(b?.payout)el.classList.add("win")});const net=r.payout-r.wager;$(".rl-result").innerHTML=`<b class="${r.color}">${r.number}</b> ${r.color.toUpperCase()}`;$(".rl-summary").innerHTML=`RETURNED <b>${ctx.money(r.payout)}</b> · NET <strong>${net>=0?"+":"−"}${ctx.money(Math.abs(net))}</strong>`;if(net>0)ctx.toast("Roulette win","win",`+${ctx.money(net)} CR net`);busy=false;render()}
 container.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||b.disabled)return;if(b.dataset.t){const k=key(b.dataset.t,b.dataset.v==null?null:+b.dataset.v),n=new Map(bets);n.set(k,(n.get(k)||0)+chip);set(n)}else if(b.dataset.chip){chip=+b.dataset.chip;render()}else if(b.dataset.tool==="undo"&&undo.length){bets=undo.pop();render()}else if(b.dataset.tool==="clear")set(new Map());else if(b.dataset.tool==="rebet"&&last)set(new Map(last));else if(b.dataset.tool==="double")set(new Map([...bets].map(([k,v])=>[k,v*2])));else if(b.classList.contains("rl-spin"))spin()});
 document.addEventListener("keydown",e=>{if(visible&&e.code==="Space"&&!e.repeat&&!e.target.closest?.("input,select,textarea")){e.preventDefault();spin()}});ctx.onModeChange(()=>{busy=false;bets=new Map();last=null;undo=[];history=load();render()});render();return{show(){visible=true;render()},hide(){visible=false}};
}
